// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package HelloWorld;

public interface DetailsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DetailsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ack = 1;</code>
   */
  java.lang.String getAck();
  /**
   * <code>string ack = 1;</code>
   */
  com.google.protobuf.ByteString
      getAckBytes();
}
