// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: biDirectional.proto

package com.dermot;

public interface DetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string emailAddress = 2;</code>
   */
  java.lang.String getEmailAddress();
  /**
   * <code>string emailAddress = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailAddressBytes();

  /**
   * <code>int32 tel = 3;</code>
   */
  int getTel();
}
