// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newService.proto

package grpc.newService;

public interface containsStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 1;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
